### ISSUE TITLE
Instruction 4 took a while to complete, intentional?

### ISSUE THREAD

**Issue by Joshua-Ronan-Phillips** [rorysedgwick/moose#14]
@rorysedgwick Instruction 4 needed a very specific set of selectors (.contentblock .intro>p>#madeforsamsung) to override the default styling in consumer.css, just using the id of #madeforsamsung was not enough, was this intentional to make it a bit harder? Wasn't sure if it was deliberate or not, but really enjoyed this repo, I think it will really help with my interview.

**Comment by rorysedgwick** [comment]
Yes this was intentional, the highly nested selector structure the company used was found to be the easiest way to be consistent across such a large codebase. I believe they actually shunned using ids at all if possible and uniformly relied of correct degrees of selector specificity to govern which css styles were applied.
Thanks for the feedback, i'm glad the repo was able to be of some help
